server:
  port: 8201

spring:
  application:
    name: sai-gateway
  profiles:
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由功能
          lower-case-service-id: true # 使用小写服务名
      routes:
        - id: sai-auth
          uri: lb://sai-auth # uri 的协议为 lb
          predicates:
            - Path=/sai-auth/**
          filters:
            - StripPrefix=1 # 匹配的请求去掉的路径个数，这里是将 /sai-auth 去掉
        - id: sai-admin
          uri: lb://sai-admin
          predicates:
            - Path=/sai-admin/**
          filters:
            - StripPrefix=1

# 自定义安全配置
secure:
  ignore:
    urls:
      - "/swagger-resources/**"
      - "/**/v3/api-docs"
      - "/swagger-ui/**"
      - "/**/*.js"
      - "/**/*.css"
      - "/**/*.png"
      - "/**/*.ico"
      - "/actuator/**"
      - "/sai-auth/oauth/token"
      - "/sai-auth/keyPair/loadPublicKey"
      - "/sai-admin/user/login"

# 自定义 Redis 配置
redis:
  database: sai
  key:
    user: user
    resources: resources
    authorities: authorities
  expire: 86400 # 秒 24 小时