server:
  port: 8081

spring:
  application:
    name: sai-search
  profiles:
    active: dev
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    rest:
      uris: 127.0.0.1:9200

management: # 开启 Spring Boot Admin 监控端点
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always