spring:
  datasource:
    url: jdbc:mysql://localhost:3306/permission?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: localhost # Redis 服务地址
    port: 6379 # Redis 服务连接端口
    database: 0 # Redis 数据库索引
    password: # Redis 服务连接密码（默认为空）
    timeout: 3000 # Redis 服务连接超时时间（毫秒）

logging:
  level:
    root: info
    com.wen.sai: debug